# Generated by Django 5.1.5 on 2025-02-10 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='voted_by',
            field=models.ManyToManyField(blank=True, related_name='voted_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
